// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Infrastructure.Persistence;

#nullable disable

namespace backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230527094722_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("backend.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerEmails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1465),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1464),
                            ManagerEmails = "anton.louf@student.ehb.be",
                            Name = ".net"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1471),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1470),
                            ManagerEmails = "anton.louf@student.ehb.be",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1473),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1472),
                            ManagerEmails = "anton.louf@student.ehb.be",
                            Name = "Low Code"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("CurrentCountOfStudents")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("MaxStudents")
                        .HasColumnType("tinyint");

                    b.Property<int>("RequiredTrainingType")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYear");

                    b.HasIndex("UnitId");

                    b.ToTable("InternShips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1569),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1568),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2022-2023",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1939),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1938),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2021-2022",
                            UnitId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2011),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2011),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2022-2023",
                            UnitId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2128),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2127),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2022-2023",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2182),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2181),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2023-2024",
                            UnitId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2462),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2462),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2022-2023",
                            UnitId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2587),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2587),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2021-2022",
                            UnitId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2812),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2812),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2021-2022",
                            UnitId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2852),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2851),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2021-2022",
                            UnitId = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2898),
                            CurrentCountOfStudents = (byte)0,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2897),
                            MaxStudents = (byte)10,
                            RequiredTrainingType = 0,
                            SchoolYear = "2023-2024",
                            UnitId = 1
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShipContentTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("InternShipId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KnowledgeToDevelop")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeededKnowledge")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TitleContent")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("InternShipId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1904),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 1,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1904),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1977),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 2,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1977),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1990),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 2,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1990),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2046),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 3,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2046),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2059),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 3,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2058),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2106),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 3,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 3,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2106),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2161),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 4,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2161),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2314),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 5,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2314),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2389),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 5,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2389),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2531),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 6,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2531),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 11,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2554),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 6,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2554),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 12,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2567),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 6,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 3,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2567),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 13,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2798),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 7,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2798),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 14,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2833),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 8,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2833),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 15,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2841),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 8,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2841),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2871),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 9,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2870),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2878),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 9,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2878),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2886),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 9,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 3,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2886),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "<p>required diploma for this internship is: Bachelor</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2918),
                            Description = "<p>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>",
                            InternShipId = 10,
                            IsDeleted = false,
                            KnowledgeToDevelop = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2918),
                            NeededKnowledge = "<p>This is a text editor</p><ul><li>With some styling</li><li>And some more styling</li><li>To test if text is converted to HTML</li></ul>",
                            TitleContent = "Standard Internship Title"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShipLocation", b =>
                {
                    b.Property<int>("InternShipId")
                        .HasColumnType("int");

                    b.Property<int>("LocationsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InternShipId", "LocationsId");

                    b.HasIndex("LocationsId");

                    b.ToTable("InternShipLocation");

                    b.HasData(
                        new
                        {
                            InternShipId = 1,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1573),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1572)
                        },
                        new
                        {
                            InternShipId = 1,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1595),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1594)
                        },
                        new
                        {
                            InternShipId = 1,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1606),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1606)
                        },
                        new
                        {
                            InternShipId = 2,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1940),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1939)
                        },
                        new
                        {
                            InternShipId = 2,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1951),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1950)
                        },
                        new
                        {
                            InternShipId = 2,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1963),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1963)
                        },
                        new
                        {
                            InternShipId = 3,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2012),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2012)
                        },
                        new
                        {
                            InternShipId = 3,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2023),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2022)
                        },
                        new
                        {
                            InternShipId = 3,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2033),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2033)
                        },
                        new
                        {
                            InternShipId = 4,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2128),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2128)
                        },
                        new
                        {
                            InternShipId = 4,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2139),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2138)
                        },
                        new
                        {
                            InternShipId = 4,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2149),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2148)
                        },
                        new
                        {
                            InternShipId = 5,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2182),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2182)
                        },
                        new
                        {
                            InternShipId = 5,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2193),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2193)
                        },
                        new
                        {
                            InternShipId = 5,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2204),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2204)
                        },
                        new
                        {
                            InternShipId = 6,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2463),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2463)
                        },
                        new
                        {
                            InternShipId = 6,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2473),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2472)
                        },
                        new
                        {
                            InternShipId = 6,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2484),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2483)
                        },
                        new
                        {
                            InternShipId = 7,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2588),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2588)
                        },
                        new
                        {
                            InternShipId = 7,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2598),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2597)
                        },
                        new
                        {
                            InternShipId = 7,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2608),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2607)
                        },
                        new
                        {
                            InternShipId = 8,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2813),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2813)
                        },
                        new
                        {
                            InternShipId = 8,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2820),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2819)
                        },
                        new
                        {
                            InternShipId = 8,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2826),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2826)
                        },
                        new
                        {
                            InternShipId = 9,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2852),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2852)
                        },
                        new
                        {
                            InternShipId = 9,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2858),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2858)
                        },
                        new
                        {
                            InternShipId = 9,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2864),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2863)
                        },
                        new
                        {
                            InternShipId = 10,
                            LocationsId = 1,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2898),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2898)
                        },
                        new
                        {
                            InternShipId = 10,
                            LocationsId = 2,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2904),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2904)
                        },
                        new
                        {
                            InternShipId = 10,
                            LocationsId = 3,
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2911),
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2911)
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Code = "en",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1458),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1458),
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "fr",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1457),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1457),
                            Name = "French"
                        },
                        new
                        {
                            Id = 1,
                            Code = "nl",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1455),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1455),
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = 4,
                            Code = "de",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1460),
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1460),
                            Name = "German"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Huizingen",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1449),
                            HouseNumber = 42,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1445),
                            StreetName = "Vaucampslaan",
                            ZipCode = "1654"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gent",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1452),
                            HouseNumber = 4,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1451),
                            StreetName = "Gaston Crommenlaan",
                            ZipCode = "9050"
                        },
                        new
                        {
                            Id = 3,
                            City = "Kontich",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1454),
                            HouseNumber = 26,
                            IsDeleted = false,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(1453),
                            StreetName = "Prins Boudewijnlaan",
                            ZipCode = "2550"
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.PrefaceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UnitId");

                    b.ToTable("PrefaceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "<p>Dit is een standaard descriptie horende bij een unit</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2938),
                            IsDeleted = false,
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2938),
                            UnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "<p>Ce ici c'est un description standard d un departement</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2970),
                            IsDeleted = false,
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2970),
                            UnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "<p>This is a standard description for a unit</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2978),
                            IsDeleted = false,
                            LanguageId = 3,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2977),
                            UnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "<p>Dit is een standaard descriptie horende bij een unit</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2985),
                            IsDeleted = false,
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2984),
                            UnitId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "<p>Ce ici c'est un description standard d un departement</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2991),
                            IsDeleted = false,
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2991),
                            UnitId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "<p>This is a standard description for a unit</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2998),
                            IsDeleted = false,
                            LanguageId = 3,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(2998),
                            UnitId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "<p>Dit is een standaard descriptie horende bij een unit</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(3005),
                            IsDeleted = false,
                            LanguageId = 1,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(3004),
                            UnitId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "<p>Ce ici c'est un description standard d un departement</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(3011),
                            IsDeleted = false,
                            LanguageId = 2,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(3011),
                            UnitId = 3
                        },
                        new
                        {
                            Id = 9,
                            Content = "<p>This is a standard description for a unit</p>",
                            CreatedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(3017),
                            IsDeleted = false,
                            LanguageId = 3,
                            LastModifiedDate = new DateTime(2023, 5, 27, 9, 47, 22, 191, DateTimeKind.Utc).AddTicks(3016),
                            UnitId = 3
                        });
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShip", b =>
                {
                    b.HasOne("backend.Domain.Entities.Department", "Unit")
                        .WithMany("Internships")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShipContentTranslation", b =>
                {
                    b.HasOne("backend.Domain.Entities.InternShip", "InternShip")
                        .WithMany("Translations")
                        .HasForeignKey("InternShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Language", "Language")
                        .WithMany("InternshipTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InternShip");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShipLocation", b =>
                {
                    b.HasOne("backend.Domain.Entities.InternShip", null)
                        .WithMany("InternShipLocations")
                        .HasForeignKey("InternShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Domain.Entities.PrefaceTranslation", b =>
                {
                    b.HasOne("backend.Domain.Entities.Language", "Language")
                        .WithMany("PrefaceTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Domain.Entities.Department", "Unit")
                        .WithMany("PrefaceTranslations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("backend.Domain.Entities.Department", b =>
                {
                    b.Navigation("Internships");

                    b.Navigation("PrefaceTranslations");
                });

            modelBuilder.Entity("backend.Domain.Entities.InternShip", b =>
                {
                    b.Navigation("InternShipLocations");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("backend.Domain.Entities.Language", b =>
                {
                    b.Navigation("InternshipTranslations");

                    b.Navigation("PrefaceTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
